[package]
name = "RustMicroservicesSandbox"
version = "0.1.0"
authors = ["Paolo Giovannini <p.giovannini@teamsystem.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
