apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  labels:
    app: RustMicroservicesSandbox
  namespace: dev
data:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: password