apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: RustMicroservicesSandbox
  namespace: dev
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_HOST_AUTH_METHOD: trust